import 'package:flutter/material.dart';

const Offset DROP_OFFSET = Offset(4, 8); //0,1
const double DROP_BLUR_RADIOUS = 1; //10
const double DROP_SPREAD = -15;

const double CLIP_BORDER_RADIOUS = 40;

TextEditingController userName = TextEditingController();

const double PAGE_PADDING = 30;

const double Elevetion = 8;

const double BIG_BUTTON_HEIGHT = 105;
const double BIG_BUTTON_FONT_SIZE = 20;

int MAXLENGTH = 1;

const List RATING_IMAGE = [
  'assets/emoticon/very good.png',
  'assets/emoticon/good.png',
  'assets/emoticon/bad.png',
  'assets/emoticon/very bad.png'
];

String INFORTEXT =
    'Zen Wave is your holistic mental wellness partner, offering a safe space to explore, understand, and enhance your emotional well-being. Its not just an app; its a companion on your journey to a healthier, happier you.';
String PRIVACYPOLICY = '''Privacy Policy

Last Updated: 23-11-2023

ZenWave is committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and safeguard your information when you use our mobile application, ZenWave.

Information We Collect

We do not collect any personal information or usage data from users of the App.

Data Storage

All data generated by the user within the App, including mood tracking, journal entries, images, and other user-created content, is stored locally on the user's device. We do not have access to or store any of this data.

Third-Party Services

The App may utilize third-party services, such as image pickers and galleries. Please review the privacy policies of these third-party services, as we are not responsible for their practices.

Data Security

We prioritize the security of your information and have implemented reasonable measures to protect it from unauthorized access, disclosure, alteration, and destruction.

User Control

Users have complete control over their data stored within the App. Users can manage account settings and preferences directly in the App. Uninstalling the App will permanently delete all locally stored data from the device.

Changes to This Privacy Policy

We may update our Privacy Policy to reflect changes in practices or for operational, legal, or regulatory reasons. Users will be notified of any changes by posting the updated Privacy Policy within the App.

Contact Us

If you have any questions or concerns about our Privacy Policy, please contact us at mohammedafreedps111@gmail.com''';
